---
name: linting
on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  rpmlint:
    name: rpmlint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install rpmlint
      - run: rpmlint -f .rpmlint -vi SPECS/*.spec
